### PR TITLE
Removing only designer wording

### PR DESCRIPTION
**Pull request by christinaforney**
I actually don't think anything else in the job description needs to change. 

@imtommyroberts - one question is if we should update this to be a "Product Designer" rather than "UX Designer" - I'm open to what you think will best resonate with the next designer we'd like to hire.

### CODE REVIEW

**Comment by imtommyroberts** [comment]
I do think we should change any mention of 'UX Designer' to 'Product Designer' across the board. It's the currently popular job title + it fits the role more closely. 

Right now the job description is fine, I would like to more closely review it in May as that's when we'll probably pick up the pressure on hiring another designer.

**Comment by christinaforney** [comment]
Updated from UX -> Product, but left the file names for now so I don't break incoming links. I don't think we have the ability to do redirects here, right?

**Comment by mercadon** [comment]
We could do that, or another solution could be that we create a new req for Product Designer and close out the existing UX Designer one.

**Comment by christinaforney** [comment]
I'd rather just update the title if possible to preserve history.

**Pull request merged**
